Added a State called MoveToXY
MRoboSub/mrobosub pull request #45
Opened 2024-11-21 01:03 UTC by imzaynb

Closes #24 

I tried to follow the format of `TurnToYaw` from `abstract_states.py`, but instead of stopping once the yaw is achieved, the robot surges forward at a speed proportional to the error between the current (x,y) and the target (x,y) until it settles at a threshold. Note that this code would be used in heavy conjunction with @RCoder01's meta state code to customize the target_x, target_y, etc.

I was looking into the PID node defined in `yaw_control.py` code and trying to think what the analogous code would be for this code, though I think heave control is good enough since this is a very rudimentary way of doing this.

Also, is `common_states.py` the file to put this in? I didn't see any other file that I liked for this.

2024-12-04 23:33 UTC, imzaynb commented
@RCoder01 @alexanderbowler When you get a chance, could you take a peek at this? Thanks!!

2025-01-12 18:30 UTC, imzaynb commented on mrobosub_planning/src/periodic_io.py
> +        cls.TargetPose.heave = target_x
should be `cls.TargetPose.x = ...`

2025-01-12 18:43 UTC, imzaynb commented on mrobosub_planning/src/common_states.py
> +                PIO.set_target_twist_surge(heave)
should be `PIO.set_target_twist_heave(heave)`

2025-01-12 18:43 UTC, imzaynb commented on mrobosub_planning/src/common_states.py
> +                PIO.set_target_twist_surge(0)
should be `PIO.set_target_twist_heave(heave)`

2025-01-23 00:09 UTC, imzaynb commented
Hey @RCoder01 . Could you give a look at this when you get a chance? Thanks!

2025-01-26 03:04 UTC, RCoder01 requested changes
Maybe instead of `angle_to_global_position` we could call it like `yaw_to_target` or something like that? And `horizontal_distance_to_target` instead of `x_y_magnitude`

Also we don't usually use type annotations on variables inside functions unless mymy demands it because it tends to just be visual noise

2025-01-30 00:36 UTC, RCoder01 approved these changes

2025-01-30 00:37 UTC, merged