Update main (finally)
MRoboSub/mrobosub pull request #5
Opened 2024-08-18 00:06 UTC by RCoder01

2024-08-18 00:23 UTC, Nolan1324 requested changes

2024-08-18 00:23 UTC, Nolan1324 commented on mrobosub_perception/launch/pathmarker.launch
This is old, we should delete this

2024-08-18 00:23 UTC, Nolan1324 commented on mrobosub_perception/launch/base_pathmarker.launch
This is old, we should delete this

2024-08-18 00:23 UTC, Nolan1324 commented on mrobosub_perception/params/pathmarker.yaml
This is old, we should delete this

2024-08-18 00:23 UTC, Nolan1324 commented on mrobosub_perception/pathmarker_pipeline.grip
This is old, we should delete this

2024-08-18 00:23 UTC, Nolan1324 commented on mrobosub_perception/src/test.png
Delete

2024-08-18 00:23 UTC, Nolan1324 commented on mrobosub_perception/src/grip_output.py
Old, delete

2024-08-18 00:23 UTC, Nolan1324 commented on mrobosub_perception/src/bbox.png
Delete

2024-08-18 00:23 UTC, Nolan1324 commented on mrobosub_perception/src/yolov5
We have this submodule twice but I am pretty sure this one does not work, delete.

2024-08-18 00:23 UTC, Nolan1324 commented on mrobosub_planning/doc/state_machine.md
Is this up to date?

2024-08-18 00:23 UTC, Nolan1324 commented on mrobosub_perception/src/pathmarker.py
Old delete

2024-08-18 00:23 UTC, Nolan1324 commented on mrobosub_perception/src/hsv_tuner.py
Old, delete

2024-08-18 00:23 UTC, Nolan1324 commented on mrobosub_perception/src/webcam_debug.py
I do not think we need this

2024-08-18 00:23 UTC, Nolan1324 commented on mrobosub_perception/src/webcam_pub.py
Rename this to botcam

2024-08-18 00:23 UTC, Nolan1324 commented on mrobosub_perception/src/webcam_sub.py
Probably do not need this

2024-08-18 00:29 UTC, Nolan1324 requested changes

2024-08-18 00:29 UTC, Nolan1324 commented on .DS_Store
Remove

2024-08-18 00:29 UTC, Nolan1324 commented on mrobosub_localization/.file
Remove

2024-08-18 00:29 UTC, Nolan1324 commented on mrobosub_msgs/srv/ObjectPosition.srv
Should probably finally add object radius and area to this.

2024-08-18 00:29 UTC, Nolan1324 commented on mrobosub_msgs/srv/HsvFilterImage.srv
I do not think this is used anymore, but double check

2024-08-18 00:29 UTC, Nolan1324 commented on mrobosub_perception/draw_bb_boxes.py
I do not think we use this anymore since we do it in the ML node now

2024-08-18 00:53 UTC, Nolan1324 commented
We probably need to also fix up quartermaster a little bit since we changed it a bit at competition

2024-08-20 21:35 UTC, RCoder01 commented on mrobosub_planning/doc/state_machine.md
Updated to mostly match the current status quo

2024-08-20 21:37 UTC, RCoder01 commented on mrobosub_msgs/srv/ObjectPosition.srv
This is a pretty involved change, I think we should pursue this after the merge

2024-08-20 21:40 UTC, RCoder01 commented on mrobosub_perception/src/yolov5
I'm having issues deleting it and having the deletions show up in git, could you try?

2024-08-20 22:30 UTC, Nolan1324 commented on mrobosub_perception/src/yolov5
I think I fixed it, I used `git rm -r --cached mrobosub_perception/src/yolov5`

2024-08-20 22:31 UTC, Nolan1324 commented on mrobosub_msgs/srv/ObjectPosition.srv
I do not think it is too bad but yeah we can delay that so that we do not have too many changes in the merge

2024-08-20 23:36 UTC, alexanderbowler approved these changes

2024-09-01 19:30 UTC, merged